import multiprocessing

DEFAULT_ERROR_CODE = 1
DEFAULT_LOGGING_FILE_PATH = "logging.cfg"
DEFAULT_LOCAL_TMP_PATH = "target/"
DEFAULT_LOCAL_ARTIFACTS_PATH = "target/artifacts/"
DEFAULT_SERVER_TMP_PATH = "/tmp/"
DEFAULT_SERVER_USERNAME = "root"
DEFAULT_SERVER_PASSWORD = "root@123"
DEFAULT_DNS_SERVER = "192.168.104.7"
DEFAULT_NTP_SERVER = "192.168.104.7"
DEFAULT_CONNECTION_TIMEOUT = 120
DEFAULT_NUM_PARALLEL_PROCESSES = int(multiprocessing.cpu_count() * 0.75)
DEFAULT_APACHE_KAFKA_TIMEOUT = 5000
DEFAULT_FILE_SERVER_IP = "192.168.192.201"
DEFAULT_FILE_SERVER_USERNAME = "root"
DEFAULT_FILE_SERVER_PASSWORD = "Gu@vu$12#"
DEFAULT_FILE_SERVER_BASE_PATH = "/var/www/html/guavus/"
DEFAULT_SMTP_SERVER = "192.168.104.25"
DEFAULT_SEPARATOR = "\t"
DEFAULT_DJANGO_SERVER_IP = "192.168.162.9"
DEFAULT_DJANGO_SERVER_PORT = "8000"
DEFAULT_DIFFLIB_LINES_THRESHOLD = 200
DEFAULT_ELASTICSEARCH_TIMEOUT = 60
DEFAULT_PAGE_SIZE = "131072"
DEFAULT_TIMESTAMP_ENV_VAR = "AUTOMATION_TIMESTAMP"
DEFAULT_DYNAMIC_SUBSTITUTION_FILE = "%s/dynamic_substitution.csv" % DEFAULT_LOCAL_ARTIFACTS_PATH
DEFAULT_ALLURE_REPORT_PATH = "%s/allure/" % DEFAULT_LOCAL_ARTIFACTS_PATH
DEFAULT_ALLURE_ENV_PATH = "%s/environment.properties" % DEFAULT_ALLURE_REPORT_PATH
DEFAULT_EXECUTION_LOGS_PATH = "%s/execution.log" % DEFAULT_LOCAL_ARTIFACTS_PATH
DEFAULT_PYTEST_REPORT_PATH = "%s/report.html" % DEFAULT_LOCAL_ARTIFACTS_PATH
DEFAULT_DATASET_ALIAS = "dataset1"

# UI default configs
DEFAULT_SELENIUM_ELEMENT_TIMEOUT = 15
